#include "defs.h"
#include "defs_debug.h"

#define X_ZERO 0

RexxTokenPair rexx_token_pair[] = {
{X_ZERO            , STRINGIFY_ENUM(X_ZERO            )},
{X_NULL            , STRINGIFY_ENUM(X_NULL            )},
{X_PROGRAM         , STRINGIFY_ENUM(X_PROGRAM         )},
{X_STATS           , STRINGIFY_ENUM(X_STATS           )},
{X_COMMAND         , STRINGIFY_ENUM(X_COMMAND         )},
{X_ADDR_V          , STRINGIFY_ENUM(X_ADDR_V          )},
{X_ADDR_N          , STRINGIFY_ENUM(X_ADDR_N          )},
{X_ADDR_S          , STRINGIFY_ENUM(X_ADDR_S          )},
{X_CALL            , STRINGIFY_ENUM(X_CALL            )},
{X_DO              , STRINGIFY_ENUM(X_DO              )},
{X_REP            , STRINGIFY_ENUM(X_REP            )},
{X_REP_FOREVER    , STRINGIFY_ENUM(X_REP_FOREVER    )},
{X_DO_TO          , STRINGIFY_ENUM(X_DO_TO          )},
{X_DO_BY          , STRINGIFY_ENUM(X_DO_BY          )},
{X_DO_FOR         , STRINGIFY_ENUM(X_DO_FOR         )},
{X_WHILE          , STRINGIFY_ENUM(X_WHILE          )},
{X_UNTIL          , STRINGIFY_ENUM(X_UNTIL          )},
{X_DROP           , STRINGIFY_ENUM(X_DROP           )},
{X_EXIT           , STRINGIFY_ENUM(X_EXIT           )},
{X_IF             , STRINGIFY_ENUM(X_IF             )},
{X_IPRET          , STRINGIFY_ENUM(X_IPRET          )},
{X_ITERATE        , STRINGIFY_ENUM(X_ITERATE        )},
{X_LABEL          , STRINGIFY_ENUM(X_LABEL          )},
{X_LEAVE          , STRINGIFY_ENUM(X_LEAVE          )},
{X_NUM_D          , STRINGIFY_ENUM(X_NUM_D          )},
{X_NUM_F          , STRINGIFY_ENUM(X_NUM_F          )},
{X_NUM_FUZZ       , STRINGIFY_ENUM(X_NUM_FUZZ       )},
{X_NUM_SCI        , STRINGIFY_ENUM(X_NUM_SCI        )},
{X_NUM_ENG        , STRINGIFY_ENUM(X_NUM_ENG        )},
{X_PARSE          , STRINGIFY_ENUM(X_PARSE          )},
{X_PARSE_ARG      , STRINGIFY_ENUM(X_PARSE_ARG      )},
{X_PARSE_EXT      , STRINGIFY_ENUM(X_PARSE_EXT      )},
{X_PARSE_PULL     , STRINGIFY_ENUM(X_PARSE_PULL     )},
{X_PARSE_SRC      , STRINGIFY_ENUM(X_PARSE_SRC      )},
{X_PARSE_VAR      , STRINGIFY_ENUM(X_PARSE_VAR      )},
{X_PARSE_VAL      , STRINGIFY_ENUM(X_PARSE_VAL      )},
{X_PARSE_VER      , STRINGIFY_ENUM(X_PARSE_VER      )},
{X_PROC           , STRINGIFY_ENUM(X_PROC           )},
{X_PULL           , STRINGIFY_ENUM(X_PULL           )},
{X_PUSH           , STRINGIFY_ENUM(X_PUSH           )},
{X_QUEUE          , STRINGIFY_ENUM(X_QUEUE          )},
{X_RETURN         , STRINGIFY_ENUM(X_RETURN         )},
{X_SAY            , STRINGIFY_ENUM(X_SAY            )},
{X_SELECT         , STRINGIFY_ENUM(X_SELECT         )},
{X_WHENS          , STRINGIFY_ENUM(X_WHENS          )},
{X_WHEN           , STRINGIFY_ENUM(X_WHEN           )},
{X_OTHERWISE      , STRINGIFY_ENUM(X_OTHERWISE      )},
{X_SIG_VAL        , STRINGIFY_ENUM(X_SIG_VAL        )},
{X_SIG_LAB        , STRINGIFY_ENUM(X_SIG_LAB        )},
{X_SIG_SET        , STRINGIFY_ENUM(X_SIG_SET        )},
{X_ON             , STRINGIFY_ENUM(X_ON             )},
{X_OFF            , STRINGIFY_ENUM(X_OFF            )},
{X_S_ERROR        , STRINGIFY_ENUM(X_S_ERROR        )},
{X_S_HALT         , STRINGIFY_ENUM(X_S_HALT         )},
{X_S_NOVALUE      , STRINGIFY_ENUM(X_S_NOVALUE      )},
{X_S_SYNTAX       , STRINGIFY_ENUM(X_S_SYNTAX       )},
{X_TRACE          , STRINGIFY_ENUM(X_TRACE          )},
{X_UPPER_VAR      , STRINGIFY_ENUM(X_UPPER_VAR      )},
{X_ASSIGN         , STRINGIFY_ENUM(X_ASSIGN         )},
{X_LOG_NOT        , STRINGIFY_ENUM(X_LOG_NOT        )},
{X_PLUSS          , STRINGIFY_ENUM(X_PLUSS          )},
{X_EQUAL          , STRINGIFY_ENUM(X_EQUAL          )},
{X_MINUS          , STRINGIFY_ENUM(X_MINUS          )},
{X_MULT           , STRINGIFY_ENUM(X_MULT           )},
{X_DEVIDE         , STRINGIFY_ENUM(X_DEVIDE         )},
{X_MODULUS        , STRINGIFY_ENUM(X_MODULUS        )},
{X_LOG_OR         , STRINGIFY_ENUM(X_LOG_OR         )},
{X_LOG_AND        , STRINGIFY_ENUM(X_LOG_AND        )},
{X_LOG_XOR        , STRINGIFY_ENUM(X_LOG_XOR        )},
{X_EXP            , STRINGIFY_ENUM(X_EXP            )},
{X_CONCAT         , STRINGIFY_ENUM(X_CONCAT         )},
{X_SPACE          , STRINGIFY_ENUM(X_SPACE          )},
{X_GTE            , STRINGIFY_ENUM(X_GTE            )},
{X_LTE            , STRINGIFY_ENUM(X_LTE            )},
{X_GT             , STRINGIFY_ENUM(X_GT             )},
{X_LT             , STRINGIFY_ENUM(X_LT             )},
{X_DIFF           , STRINGIFY_ENUM(X_DIFF           )},
{X_SIM_SYMBOL     , STRINGIFY_ENUM(X_SIM_SYMBOL     )},
{X_CON_SYMBOL     , STRINGIFY_ENUM(X_CON_SYMBOL     )},
{X_STRING         , STRINGIFY_ENUM(X_STRING         )},
{X_U_MINUS        , STRINGIFY_ENUM(X_U_MINUS        )},
{X_S_EQUAL        , STRINGIFY_ENUM(X_S_EQUAL        )},
{X_S_DIFF         , STRINGIFY_ENUM(X_S_DIFF         )},
{X_INTDIV         , STRINGIFY_ENUM(X_INTDIV         )},
{X_EX_FUNC        , STRINGIFY_ENUM(X_EX_FUNC        )},
{X_IN_FUNC        , STRINGIFY_ENUM(X_IN_FUNC        )},
{X_TPL_SOLID      , STRINGIFY_ENUM(X_TPL_SOLID      )},
{X_TPL_MVE        , STRINGIFY_ENUM(X_TPL_MVE        )},
{X_TPL_VAR        , STRINGIFY_ENUM(X_TPL_VAR        )},
{X_TPL_SYMBOL     , STRINGIFY_ENUM(X_TPL_SYMBOL     )},
{X_TPL_POINT      , STRINGIFY_ENUM(X_TPL_POINT      )},
{X_POS_OFFS       , STRINGIFY_ENUM(X_POS_OFFS       )},
{X_NEG_OFFS       , STRINGIFY_ENUM(X_NEG_OFFS       )},
{X_ABS_OFFS       , STRINGIFY_ENUM(X_ABS_OFFS       )},
{X_EXPRLIST       , STRINGIFY_ENUM(X_EXPRLIST       )},
{X_S_NOTREADY     , STRINGIFY_ENUM(X_S_NOTREADY     )},
{X_S_FAILURE      , STRINGIFY_ENUM(X_S_FAILURE      )},
{X_END            , STRINGIFY_ENUM(X_END            )},
{X_CALL_SET       , STRINGIFY_ENUM(X_CALL_SET       )},
{X_NO_OTHERWISE   , STRINGIFY_ENUM(X_NO_OTHERWISE   )},
{X_IND_SYMBOL    , STRINGIFY_ENUM(X_IND_SYMBOL    )},
{X_IS_INTERNAL   , STRINGIFY_ENUM(X_IS_INTERNAL   )},
{X_IS_BUILTIN    , STRINGIFY_ENUM(X_IS_BUILTIN    )},
{X_IS_EXTERNAL   , STRINGIFY_ENUM(X_IS_EXTERNAL   )},
{X_CTAIL_SYMBOL  , STRINGIFY_ENUM(X_CTAIL_SYMBOL  )},
{X_VTAIL_SYMBOL  , STRINGIFY_ENUM(X_VTAIL_SYMBOL  )},
{X_HEAD_SYMBOL   , STRINGIFY_ENUM(X_HEAD_SYMBOL   )},
{X_STEM_SYMBOL   , STRINGIFY_ENUM(X_STEM_SYMBOL   )},
{X_SEQUAL        , STRINGIFY_ENUM(X_SEQUAL        )},
{X_SDIFF         , STRINGIFY_ENUM(X_SDIFF         )},
{X_SGT           , STRINGIFY_ENUM(X_SGT           )},
{X_SGTE          , STRINGIFY_ENUM(X_SGTE          )},
{X_SLT           , STRINGIFY_ENUM(X_SLT           )},
{X_SLTE          , STRINGIFY_ENUM(X_SLTE          )},
{X_NEQUAL        , STRINGIFY_ENUM(X_NEQUAL        )},
{X_NDIFF         , STRINGIFY_ENUM(X_NDIFF         )},
{X_NGT           , STRINGIFY_ENUM(X_NGT           )},
{X_NGTE          , STRINGIFY_ENUM(X_NGTE          )},
{X_NLT           , STRINGIFY_ENUM(X_NLT           )},
{X_NLTE          , STRINGIFY_ENUM(X_NLTE          )},
{X_NASSIGN       , STRINGIFY_ENUM(X_NASSIGN       )},
{X_CEXPRLIST     , STRINGIFY_ENUM(X_CEXPRLIST     )},
{X_U_PLUSS       , STRINGIFY_ENUM(X_U_PLUSS       )},
{X_OPTIONS       , STRINGIFY_ENUM(X_OPTIONS       )},
{X_NUM_V         , STRINGIFY_ENUM(X_NUM_V         )},
{X_NUM_DDEF      , STRINGIFY_ENUM(X_NUM_DDEF      )},
{X_NUM_FDEF      , STRINGIFY_ENUM(X_NUM_FDEF      )},
{X_NUM_FRMDEF    , STRINGIFY_ENUM(X_NUM_FRMDEF    )},
{X_S_NGT         , STRINGIFY_ENUM(X_S_NGT         )},
{X_S_NLT         , STRINGIFY_ENUM(X_S_NLT         )},
{X_S_GT          , STRINGIFY_ENUM(X_S_GT          )},
{X_S_GTE         , STRINGIFY_ENUM(X_S_GTE         )},
{X_S_LT          , STRINGIFY_ENUM(X_S_LT          )},
{X_S_LTE         , STRINGIFY_ENUM(X_S_LTE         )},
{X_ADDR_WITH     , STRINGIFY_ENUM(X_ADDR_WITH     )},
{X_S_LOSTDIGITS  , STRINGIFY_ENUM(X_S_LOSTDIGITS  )},
{X_DO_EXPR       , STRINGIFY_ENUM(X_DO_EXPR       )},
{X_PLUSASSIGN    , STRINGIFY_ENUM(X_PLUSASSIGN    )},
{X_MINUSASSIGN   , STRINGIFY_ENUM(X_MINUSASSIGN   )},
{X_MULTASSIGN    , STRINGIFY_ENUM(X_MULTASSIGN    )},
{X_DIVASSIGN     , STRINGIFY_ENUM(X_DIVASSIGN     )},
{X_INTDIVASSIGN  , STRINGIFY_ENUM(X_INTDIVASSIGN  )},
{X_MODULUSASSIGN , STRINGIFY_ENUM(X_MODULUSASSIGN )},
{X_ORASSIGN      , STRINGIFY_ENUM(X_ORASSIGN      )},
{X_XORASSIGN     , STRINGIFY_ENUM(X_XORASSIGN     )},
{X_ANDASSIGN     , STRINGIFY_ENUM(X_ANDASSIGN     )},
{X_CONCATASSIGN  , STRINGIFY_ENUM(X_CONCATASSIGN  )},
{X_PARSE_NUM     , STRINGIFY_ENUM(X_PARSE_NUM     )}
};

const char *get_rexx_type_text(int type)
{
    if ( type < 0 || type >= sizeof(rexx_token_pair)/sizeof(rexx_token_pair[0]) ) {
        return 0;
    }
    return rexx_token_pair[type].type_text;
}

void debug_print_hex_buf(FILE *fp,
    const char buf[],
    unsigned int len)
{
    int i;
    fprintf(fp, "------- buf(%p) len(%u)", buf, len);
    for ( i = 0 ; i < len ; i++ ) {
        if ( !(i%32) ) {
            fprintf(fp, "\n%p:    ", &buf[i]);
        }
        if ( i%32 && !(i%8) ) {
            fprintf(fp, ":");
        }
        fprintf(fp, "%02x", (unsigned char )buf[i]);
    }
    fprintf(fp, "\n-------\n");
    fflush(stderr);
}

